/*
	Generated by KBEngine!
	Please do not modify this file!
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	public class EntityDef
	{
		public static Dictionary<string, UInt16> datatype2id = new Dictionary<string, UInt16>();
		public static Dictionary<string, DATATYPE_BASE> datatypes = new Dictionary<string, DATATYPE_BASE>();
		public static Dictionary<UInt16, DATATYPE_BASE> id2datatypes = new Dictionary<UInt16, DATATYPE_BASE>();
		public static Dictionary<string, Int32> entityclass = new Dictionary<string, Int32>();
		public static Dictionary<string, ScriptModule> moduledefs = new Dictionary<string, ScriptModule>();
		public static Dictionary<UInt16, ScriptModule> idmoduledefs = new Dictionary<UInt16, ScriptModule>();

		public static bool init()
		{
			initDataTypes();
			initDefTypes();
			initScriptModules();
			return true;
		}

		public static bool reset()
		{
			clear();
			return init();
		}

		public static void clear()
		{
			datatype2id.Clear();
			datatypes.Clear();
			id2datatypes.Clear();
			entityclass.Clear();
			moduledefs.Clear();
			idmoduledefs.Clear();
		}

		public static void initDataTypes()
		{
			datatypes["UINT8"] = new DATATYPE_UINT8();
			datatypes["UINT16"] = new DATATYPE_UINT16();
			datatypes["UINT32"] = new DATATYPE_UINT32();
			datatypes["UINT64"] = new DATATYPE_UINT64();

			datatypes["INT8"] = new DATATYPE_INT8();
			datatypes["INT16"] = new DATATYPE_INT16();
			datatypes["INT32"] = new DATATYPE_INT32();
			datatypes["INT64"] = new DATATYPE_INT64();

			datatypes["FLOAT"] = new DATATYPE_FLOAT();
			datatypes["DOUBLE"] = new DATATYPE_DOUBLE();

			datatypes["STRING"] = new DATATYPE_STRING();
			datatypes["VECTOR2"] = new DATATYPE_VECTOR2();

			datatypes["VECTOR3"] = new DATATYPE_VECTOR3();

			datatypes["VECTOR4"] = new DATATYPE_VECTOR4();
			datatypes["PYTHON"] = new DATATYPE_PYTHON();

			datatypes["UNICODE"] = new DATATYPE_UNICODE();
			datatypes["ENTITYCALL"] = new DATATYPE_ENTITYCALL();

			datatypes["BLOB"] = new DATATYPE_BLOB();
		}

		public static void initScriptModules()
		{
			ScriptModule pAccountModule = new ScriptModule("Account");
			EntityDef.moduledefs["Account"] = pAccountModule;
			EntityDef.idmoduledefs[1] = pAccountModule;

			Property pAccount_position = new Property();
			pAccount_position.name = "position";
			pAccount_position.properUtype = 40000;
			pAccount_position.properFlags = 4;
			pAccount_position.aliasID = 1;
			Vector3 Account_position_defval = new Vector3();
			pAccount_position.defaultVal = Account_position_defval;
			pAccountModule.propertys["position"] = pAccount_position; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_position.aliasID] = pAccount_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(position / 40000).");

			Property pAccount_direction = new Property();
			pAccount_direction.name = "direction";
			pAccount_direction.properUtype = 40001;
			pAccount_direction.properFlags = 4;
			pAccount_direction.aliasID = 2;
			Vector3 Account_direction_defval = new Vector3();
			pAccount_direction.defaultVal = Account_direction_defval;
			pAccountModule.propertys["direction"] = pAccount_direction; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_direction.aliasID] = pAccount_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(direction / 40001).");

			Property pAccount_spaceID = new Property();
			pAccount_spaceID.name = "spaceID";
			pAccount_spaceID.properUtype = 40002;
			pAccount_spaceID.properFlags = 16;
			pAccount_spaceID.aliasID = 3;
			UInt32 Account_spaceID_defval;
			UInt32.TryParse("", out Account_spaceID_defval);
			pAccount_spaceID.defaultVal = Account_spaceID_defval;
			pAccountModule.propertys["spaceID"] = pAccount_spaceID; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_spaceID.aliasID] = pAccount_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(spaceID / 40002).");

			Property pAccount_friendList = new Property();
			pAccount_friendList.name = "friendList";
			pAccount_friendList.properUtype = 8;
			pAccount_friendList.properFlags = 32;
			pAccount_friendList.aliasID = 4;
			pAccount_friendList.defaultVal = EntityDef.id2datatypes[24].parseDefaultValStr("[]");
			pAccountModule.propertys["friendList"] = pAccount_friendList; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_friendList.aliasID] = pAccount_friendList;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(friendList / 8).");

			Property pAccount_playerBean = new Property();
			pAccount_playerBean.name = "playerBean";
			pAccount_playerBean.properUtype = 3;
			pAccount_playerBean.properFlags = 32;
			pAccount_playerBean.aliasID = 5;
			Int32 Account_playerBean_defval;
			Int32.TryParse("", out Account_playerBean_defval);
			pAccount_playerBean.defaultVal = Account_playerBean_defval;
			pAccountModule.propertys["playerBean"] = pAccount_playerBean; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerBean.aliasID] = pAccount_playerBean;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerBean / 3).");

			Property pAccount_playerData = new Property();
			pAccount_playerData.name = "playerData";
			pAccount_playerData.properUtype = 6;
			pAccount_playerData.properFlags = 4;
			pAccount_playerData.aliasID = 6;
			pAccount_playerData.defaultVal = EntityDef.id2datatypes[25].parseDefaultValStr("");
			pAccountModule.propertys["playerData"] = pAccount_playerData; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerData.aliasID] = pAccount_playerData;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerData / 6).");

			Property pAccount_playerId = new Property();
			pAccount_playerId.name = "playerId";
			pAccount_playerId.properUtype = 2;
			pAccount_playerId.properFlags = 32;
			pAccount_playerId.aliasID = 7;
			UInt16 Account_playerId_defval;
			UInt16.TryParse("", out Account_playerId_defval);
			pAccount_playerId.defaultVal = Account_playerId_defval;
			pAccountModule.propertys["playerId"] = pAccount_playerId; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerId.aliasID] = pAccount_playerId;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerId / 2).");

			Property pAccount_playerName = new Property();
			pAccount_playerName.name = "playerName";
			pAccount_playerName.properUtype = 1;
			pAccount_playerName.properFlags = 32;
			pAccount_playerName.aliasID = 8;
			string Account_playerName_defval = "";
			pAccount_playerName.defaultVal = Account_playerName_defval;
			pAccountModule.propertys["playerName"] = pAccount_playerName; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerName.aliasID] = pAccount_playerName;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerName / 1).");

			Property pAccount_playerNew = new Property();
			pAccount_playerNew.name = "playerNew";
			pAccount_playerNew.properUtype = 4;
			pAccount_playerNew.properFlags = 32;
			pAccount_playerNew.aliasID = 9;
			Byte Account_playerNew_defval;
			Byte.TryParse("1", out Account_playerNew_defval);
			pAccount_playerNew.defaultVal = Account_playerNew_defval;
			pAccountModule.propertys["playerNew"] = pAccount_playerNew; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerNew.aliasID] = pAccount_playerNew;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerNew / 4).");

			Property pAccount_playerPoker = new Property();
			pAccount_playerPoker.name = "playerPoker";
			pAccount_playerPoker.properUtype = 7;
			pAccount_playerPoker.properFlags = 16;
			pAccount_playerPoker.aliasID = 10;
			pAccount_playerPoker.defaultVal = EntityDef.id2datatypes[23].parseDefaultValStr("");
			pAccountModule.propertys["playerPoker"] = pAccount_playerPoker; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_playerPoker.aliasID] = pAccount_playerPoker;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(playerPoker / 7).");

			Property pAccount_roomIndex = new Property();
			pAccount_roomIndex.name = "roomIndex";
			pAccount_roomIndex.properUtype = 5;
			pAccount_roomIndex.properFlags = 32;
			pAccount_roomIndex.aliasID = 11;
			Byte Account_roomIndex_defval;
			Byte.TryParse("", out Account_roomIndex_defval);
			pAccount_roomIndex.defaultVal = Account_roomIndex_defval;
			pAccountModule.propertys["roomIndex"] = pAccount_roomIndex; 

			pAccountModule.usePropertyDescrAlias = true;
			pAccountModule.idpropertys[(UInt16)pAccount_roomIndex.aliasID] = pAccount_roomIndex;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), property(roomIndex / 5).");

			List<DATATYPE_BASE> pAccount_displayPoker_args = new List<DATATYPE_BASE>();
			pAccount_displayPoker_args.Add(EntityDef.id2datatypes[23]);

			Method pAccount_displayPoker = new Method();
			pAccount_displayPoker.name = "displayPoker";
			pAccount_displayPoker.methodUtype = 33;
			pAccount_displayPoker.aliasID = 1;
			pAccount_displayPoker.args = pAccount_displayPoker_args;

			pAccountModule.methods["displayPoker"] = pAccount_displayPoker; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_displayPoker.aliasID] = pAccount_displayPoker;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(displayPoker / 33).");

			List<DATATYPE_BASE> pAccount_friendListData_args = new List<DATATYPE_BASE>();
			pAccount_friendListData_args.Add(EntityDef.id2datatypes[30]);

			Method pAccount_friendListData = new Method();
			pAccount_friendListData.name = "friendListData";
			pAccount_friendListData.methodUtype = 37;
			pAccount_friendListData.aliasID = 2;
			pAccount_friendListData.args = pAccount_friendListData_args;

			pAccountModule.methods["friendListData"] = pAccount_friendListData; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_friendListData.aliasID] = pAccount_friendListData;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(friendListData / 37).");

			List<DATATYPE_BASE> pAccount_initGamePoker_args = new List<DATATYPE_BASE>();

			Method pAccount_initGamePoker = new Method();
			pAccount_initGamePoker.name = "initGamePoker";
			pAccount_initGamePoker.methodUtype = 26;
			pAccount_initGamePoker.aliasID = 3;
			pAccount_initGamePoker.args = pAccount_initGamePoker_args;

			pAccountModule.methods["initGamePoker"] = pAccount_initGamePoker; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_initGamePoker.aliasID] = pAccount_initGamePoker;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(initGamePoker / 26).");

			List<DATATYPE_BASE> pAccount_loadLandlordPoker_args = new List<DATATYPE_BASE>();
			pAccount_loadLandlordPoker_args.Add(EntityDef.id2datatypes[6]);
			pAccount_loadLandlordPoker_args.Add(EntityDef.id2datatypes[23]);

			Method pAccount_loadLandlordPoker = new Method();
			pAccount_loadLandlordPoker.name = "loadLandlordPoker";
			pAccount_loadLandlordPoker.methodUtype = 31;
			pAccount_loadLandlordPoker.aliasID = 4;
			pAccount_loadLandlordPoker.args = pAccount_loadLandlordPoker_args;

			pAccountModule.methods["loadLandlordPoker"] = pAccount_loadLandlordPoker; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_loadLandlordPoker.aliasID] = pAccount_loadLandlordPoker;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(loadLandlordPoker / 31).");

			List<DATATYPE_BASE> pAccount_notifyToCallLandlord_args = new List<DATATYPE_BASE>();

			Method pAccount_notifyToCallLandlord = new Method();
			pAccount_notifyToCallLandlord.name = "notifyToCallLandlord";
			pAccount_notifyToCallLandlord.methodUtype = 27;
			pAccount_notifyToCallLandlord.aliasID = 5;
			pAccount_notifyToCallLandlord.args = pAccount_notifyToCallLandlord_args;

			pAccountModule.methods["notifyToCallLandlord"] = pAccount_notifyToCallLandlord; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_notifyToCallLandlord.aliasID] = pAccount_notifyToCallLandlord;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(notifyToCallLandlord / 27).");

			List<DATATYPE_BASE> pAccount_notifyToPlayPoker_args = new List<DATATYPE_BASE>();
			pAccount_notifyToPlayPoker_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_notifyToPlayPoker = new Method();
			pAccount_notifyToPlayPoker.name = "notifyToPlayPoker";
			pAccount_notifyToPlayPoker.methodUtype = 28;
			pAccount_notifyToPlayPoker.aliasID = 6;
			pAccount_notifyToPlayPoker.args = pAccount_notifyToPlayPoker_args;

			pAccountModule.methods["notifyToPlayPoker"] = pAccount_notifyToPlayPoker; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_notifyToPlayPoker.aliasID] = pAccount_notifyToPlayPoker;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(notifyToPlayPoker / 28).");

			List<DATATYPE_BASE> pAccount_passPoker_args = new List<DATATYPE_BASE>();

			Method pAccount_passPoker = new Method();
			pAccount_passPoker.name = "passPoker";
			pAccount_passPoker.methodUtype = 34;
			pAccount_passPoker.aliasID = 7;
			pAccount_passPoker.args = pAccount_passPoker_args;

			pAccountModule.methods["passPoker"] = pAccount_passPoker; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_passPoker.aliasID] = pAccount_passPoker;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(passPoker / 34).");

			List<DATATYPE_BASE> pAccount_playPokerFailed_args = new List<DATATYPE_BASE>();

			Method pAccount_playPokerFailed = new Method();
			pAccount_playPokerFailed.name = "playPokerFailed";
			pAccount_playPokerFailed.methodUtype = 32;
			pAccount_playPokerFailed.aliasID = 8;
			pAccount_playPokerFailed.args = pAccount_playPokerFailed_args;

			pAccountModule.methods["playPokerFailed"] = pAccount_playPokerFailed; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_playPokerFailed.aliasID] = pAccount_playPokerFailed;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playPokerFailed / 32).");

			List<DATATYPE_BASE> pAccount_playerReadyGame_args = new List<DATATYPE_BASE>();
			pAccount_playerReadyGame_args.Add(EntityDef.id2datatypes[6]);
			pAccount_playerReadyGame_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_playerReadyGame = new Method();
			pAccount_playerReadyGame.name = "playerReadyGame";
			pAccount_playerReadyGame.methodUtype = 29;
			pAccount_playerReadyGame.aliasID = 9;
			pAccount_playerReadyGame.args = pAccount_playerReadyGame_args;

			pAccountModule.methods["playerReadyGame"] = pAccount_playerReadyGame; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_playerReadyGame.aliasID] = pAccount_playerReadyGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerReadyGame / 29).");

			List<DATATYPE_BASE> pAccount_playerToLandlord_args = new List<DATATYPE_BASE>();
			pAccount_playerToLandlord_args.Add(EntityDef.id2datatypes[6]);
			pAccount_playerToLandlord_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_playerToLandlord = new Method();
			pAccount_playerToLandlord.name = "playerToLandlord";
			pAccount_playerToLandlord.methodUtype = 30;
			pAccount_playerToLandlord.aliasID = 10;
			pAccount_playerToLandlord.args = pAccount_playerToLandlord_args;

			pAccountModule.methods["playerToLandlord"] = pAccount_playerToLandlord; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_playerToLandlord.aliasID] = pAccount_playerToLandlord;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerToLandlord / 30).");

			List<DATATYPE_BASE> pAccount_pokerGameOver_args = new List<DATATYPE_BASE>();
			pAccount_pokerGameOver_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_pokerGameOver = new Method();
			pAccount_pokerGameOver.name = "pokerGameOver";
			pAccount_pokerGameOver.methodUtype = 35;
			pAccount_pokerGameOver.aliasID = 11;
			pAccount_pokerGameOver.args = pAccount_pokerGameOver_args;

			pAccountModule.methods["pokerGameOver"] = pAccount_pokerGameOver; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_pokerGameOver.aliasID] = pAccount_pokerGameOver;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(pokerGameOver / 35).");

			List<DATATYPE_BASE> pAccount_receiveMail_args = new List<DATATYPE_BASE>();
			pAccount_receiveMail_args.Add(EntityDef.id2datatypes[26]);

			Method pAccount_receiveMail = new Method();
			pAccount_receiveMail.name = "receiveMail";
			pAccount_receiveMail.methodUtype = 36;
			pAccount_receiveMail.aliasID = 12;
			pAccount_receiveMail.args = pAccount_receiveMail_args;

			pAccountModule.methods["receiveMail"] = pAccount_receiveMail; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_receiveMail.aliasID] = pAccount_receiveMail;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(receiveMail / 36).");

			List<DATATYPE_BASE> pAccount_returnErrorMessage_args = new List<DATATYPE_BASE>();
			pAccount_returnErrorMessage_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_returnErrorMessage = new Method();
			pAccount_returnErrorMessage.name = "returnErrorMessage";
			pAccount_returnErrorMessage.methodUtype = 25;
			pAccount_returnErrorMessage.aliasID = 13;
			pAccount_returnErrorMessage.args = pAccount_returnErrorMessage_args;

			pAccountModule.methods["returnErrorMessage"] = pAccount_returnErrorMessage; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_returnErrorMessage.aliasID] = pAccount_returnErrorMessage;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(returnErrorMessage / 25).");

			List<DATATYPE_BASE> pAccount_stayInRoom_args = new List<DATATYPE_BASE>();
			pAccount_stayInRoom_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_stayInRoom = new Method();
			pAccount_stayInRoom.name = "stayInRoom";
			pAccount_stayInRoom.methodUtype = 38;
			pAccount_stayInRoom.aliasID = 14;
			pAccount_stayInRoom.args = pAccount_stayInRoom_args;

			pAccountModule.methods["stayInRoom"] = pAccount_stayInRoom; 
			pAccountModule.useMethodDescrAlias = true;
			pAccountModule.idmethods[(UInt16)pAccount_stayInRoom.aliasID] = pAccount_stayInRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(stayInRoom / 38).");

			List<DATATYPE_BASE> pAccount_getFriendListData_args = new List<DATATYPE_BASE>();

			Method pAccount_getFriendListData = new Method();
			pAccount_getFriendListData.name = "getFriendListData";
			pAccount_getFriendListData.methodUtype = 21;
			pAccount_getFriendListData.aliasID = -1;
			pAccount_getFriendListData.args = pAccount_getFriendListData_args;

			pAccountModule.methods["getFriendListData"] = pAccount_getFriendListData; 
			pAccountModule.base_methods["getFriendListData"] = pAccount_getFriendListData;

			pAccountModule.idbase_methods[pAccount_getFriendListData.methodUtype] = pAccount_getFriendListData;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(getFriendListData / 21).");

			List<DATATYPE_BASE> pAccount_playerAgreeFriend_args = new List<DATATYPE_BASE>();
			pAccount_playerAgreeFriend_args.Add(EntityDef.id2datatypes[5]);
			pAccount_playerAgreeFriend_args.Add(EntityDef.id2datatypes[2]);

			Method pAccount_playerAgreeFriend = new Method();
			pAccount_playerAgreeFriend.name = "playerAgreeFriend";
			pAccount_playerAgreeFriend.methodUtype = 22;
			pAccount_playerAgreeFriend.aliasID = -1;
			pAccount_playerAgreeFriend.args = pAccount_playerAgreeFriend_args;

			pAccountModule.methods["playerAgreeFriend"] = pAccount_playerAgreeFriend; 
			pAccountModule.base_methods["playerAgreeFriend"] = pAccount_playerAgreeFriend;

			pAccountModule.idbase_methods[pAccount_playerAgreeFriend.methodUtype] = pAccount_playerAgreeFriend;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerAgreeFriend / 22).");

			List<DATATYPE_BASE> pAccount_playerCreateGame_args = new List<DATATYPE_BASE>();
			pAccount_playerCreateGame_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_playerCreateGame = new Method();
			pAccount_playerCreateGame.name = "playerCreateGame";
			pAccount_playerCreateGame.methodUtype = 13;
			pAccount_playerCreateGame.aliasID = -1;
			pAccount_playerCreateGame.args = pAccount_playerCreateGame_args;

			pAccountModule.methods["playerCreateGame"] = pAccount_playerCreateGame; 
			pAccountModule.base_methods["playerCreateGame"] = pAccount_playerCreateGame;

			pAccountModule.idbase_methods[pAccount_playerCreateGame.methodUtype] = pAccount_playerCreateGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerCreateGame / 13).");

			List<DATATYPE_BASE> pAccount_playerJoinGame_args = new List<DATATYPE_BASE>();
			pAccount_playerJoinGame_args.Add(EntityDef.id2datatypes[9]);

			Method pAccount_playerJoinGame = new Method();
			pAccount_playerJoinGame.name = "playerJoinGame";
			pAccount_playerJoinGame.methodUtype = 12;
			pAccount_playerJoinGame.aliasID = -1;
			pAccount_playerJoinGame.args = pAccount_playerJoinGame_args;

			pAccountModule.methods["playerJoinGame"] = pAccount_playerJoinGame; 
			pAccountModule.base_methods["playerJoinGame"] = pAccount_playerJoinGame;

			pAccountModule.idbase_methods[pAccount_playerJoinGame.methodUtype] = pAccount_playerJoinGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerJoinGame / 12).");

			List<DATATYPE_BASE> pAccount_playerLeaveRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_playerLeaveRoom = new Method();
			pAccount_playerLeaveRoom.name = "playerLeaveRoom";
			pAccount_playerLeaveRoom.methodUtype = 14;
			pAccount_playerLeaveRoom.aliasID = -1;
			pAccount_playerLeaveRoom.args = pAccount_playerLeaveRoom_args;

			pAccountModule.methods["playerLeaveRoom"] = pAccount_playerLeaveRoom; 
			pAccountModule.base_methods["playerLeaveRoom"] = pAccount_playerLeaveRoom;

			pAccountModule.idbase_methods[pAccount_playerLeaveRoom.methodUtype] = pAccount_playerLeaveRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerLeaveRoom / 14).");

			List<DATATYPE_BASE> pAccount_playerMatchGame_args = new List<DATATYPE_BASE>();

			Method pAccount_playerMatchGame = new Method();
			pAccount_playerMatchGame.name = "playerMatchGame";
			pAccount_playerMatchGame.methodUtype = 11;
			pAccount_playerMatchGame.aliasID = -1;
			pAccount_playerMatchGame.args = pAccount_playerMatchGame_args;

			pAccountModule.methods["playerMatchGame"] = pAccount_playerMatchGame; 
			pAccountModule.base_methods["playerMatchGame"] = pAccount_playerMatchGame;

			pAccountModule.idbase_methods[pAccount_playerMatchGame.methodUtype] = pAccount_playerMatchGame;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerMatchGame / 11).");

			List<DATATYPE_BASE> pAccount_playerSendMail_args = new List<DATATYPE_BASE>();
			pAccount_playerSendMail_args.Add(EntityDef.id2datatypes[5]);

			Method pAccount_playerSendMail = new Method();
			pAccount_playerSendMail.name = "playerSendMail";
			pAccount_playerSendMail.methodUtype = 19;
			pAccount_playerSendMail.aliasID = -1;
			pAccount_playerSendMail.args = pAccount_playerSendMail_args;

			pAccountModule.methods["playerSendMail"] = pAccount_playerSendMail; 
			pAccountModule.base_methods["playerSendMail"] = pAccount_playerSendMail;

			pAccountModule.idbase_methods[pAccount_playerSendMail.methodUtype] = pAccount_playerSendMail;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerSendMail / 19).");

			List<DATATYPE_BASE> pAccount_reqPlayerMail_args = new List<DATATYPE_BASE>();

			Method pAccount_reqPlayerMail = new Method();
			pAccount_reqPlayerMail.name = "reqPlayerMail";
			pAccount_reqPlayerMail.methodUtype = 23;
			pAccount_reqPlayerMail.aliasID = -1;
			pAccount_reqPlayerMail.args = pAccount_reqPlayerMail_args;

			pAccountModule.methods["reqPlayerMail"] = pAccount_reqPlayerMail; 
			pAccountModule.base_methods["reqPlayerMail"] = pAccount_reqPlayerMail;

			pAccountModule.idbase_methods[pAccount_reqPlayerMail.methodUtype] = pAccount_reqPlayerMail;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(reqPlayerMail / 23).");

			List<DATATYPE_BASE> pAccount_leaveRoom_args = new List<DATATYPE_BASE>();

			Method pAccount_leaveRoom = new Method();
			pAccount_leaveRoom.name = "leaveRoom";
			pAccount_leaveRoom.methodUtype = 9;
			pAccount_leaveRoom.aliasID = -1;
			pAccount_leaveRoom.args = pAccount_leaveRoom_args;

			pAccountModule.methods["leaveRoom"] = pAccount_leaveRoom; 
			pAccountModule.cell_methods["leaveRoom"] = pAccount_leaveRoom;

			pAccountModule.idcell_methods[pAccount_leaveRoom.methodUtype] = pAccount_leaveRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(leaveRoom / 9).");

			List<DATATYPE_BASE> pAccount_playerMakeLandlord_args = new List<DATATYPE_BASE>();
			pAccount_playerMakeLandlord_args.Add(EntityDef.id2datatypes[6]);
			pAccount_playerMakeLandlord_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_playerMakeLandlord = new Method();
			pAccount_playerMakeLandlord.name = "playerMakeLandlord";
			pAccount_playerMakeLandlord.methodUtype = 4;
			pAccount_playerMakeLandlord.aliasID = -1;
			pAccount_playerMakeLandlord.args = pAccount_playerMakeLandlord_args;

			pAccountModule.methods["playerMakeLandlord"] = pAccount_playerMakeLandlord; 
			pAccountModule.cell_methods["playerMakeLandlord"] = pAccount_playerMakeLandlord;

			pAccountModule.idcell_methods[pAccount_playerMakeLandlord.methodUtype] = pAccount_playerMakeLandlord;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(playerMakeLandlord / 4).");

			List<DATATYPE_BASE> pAccount_setGameReady_args = new List<DATATYPE_BASE>();
			pAccount_setGameReady_args.Add(EntityDef.id2datatypes[6]);

			Method pAccount_setGameReady = new Method();
			pAccount_setGameReady.name = "setGameReady";
			pAccount_setGameReady.methodUtype = 2;
			pAccount_setGameReady.aliasID = -1;
			pAccount_setGameReady.args = pAccount_setGameReady_args;

			pAccountModule.methods["setGameReady"] = pAccount_setGameReady; 
			pAccountModule.cell_methods["setGameReady"] = pAccount_setGameReady;

			pAccountModule.idcell_methods[pAccount_setGameReady.methodUtype] = pAccount_setGameReady;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(setGameReady / 2).");

			List<DATATYPE_BASE> pAccount_stayRoom_args = new List<DATATYPE_BASE>();
			pAccount_stayRoom_args.Add(EntityDef.id2datatypes[8]);

			Method pAccount_stayRoom = new Method();
			pAccount_stayRoom.name = "stayRoom";
			pAccount_stayRoom.methodUtype = 10;
			pAccount_stayRoom.aliasID = -1;
			pAccount_stayRoom.args = pAccount_stayRoom_args;

			pAccountModule.methods["stayRoom"] = pAccount_stayRoom; 
			pAccountModule.cell_methods["stayRoom"] = pAccount_stayRoom;

			pAccountModule.idcell_methods[pAccount_stayRoom.methodUtype] = pAccount_stayRoom;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Account), method(stayRoom / 10).");

			ScriptModule pRoomModule = new ScriptModule("Room");
			EntityDef.moduledefs["Room"] = pRoomModule;
			EntityDef.idmoduledefs[3] = pRoomModule;

			Property pRoom_position = new Property();
			pRoom_position.name = "position";
			pRoom_position.properUtype = 40000;
			pRoom_position.properFlags = 4;
			pRoom_position.aliasID = 1;
			Vector3 Room_position_defval = new Vector3();
			pRoom_position.defaultVal = Room_position_defval;
			pRoomModule.propertys["position"] = pRoom_position; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_position.aliasID] = pRoom_position;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(position / 40000).");

			Property pRoom_direction = new Property();
			pRoom_direction.name = "direction";
			pRoom_direction.properUtype = 40001;
			pRoom_direction.properFlags = 4;
			pRoom_direction.aliasID = 2;
			Vector3 Room_direction_defval = new Vector3();
			pRoom_direction.defaultVal = Room_direction_defval;
			pRoomModule.propertys["direction"] = pRoom_direction; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_direction.aliasID] = pRoom_direction;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(direction / 40001).");

			Property pRoom_spaceID = new Property();
			pRoom_spaceID.name = "spaceID";
			pRoom_spaceID.properUtype = 40002;
			pRoom_spaceID.properFlags = 16;
			pRoom_spaceID.aliasID = 3;
			UInt32 Room_spaceID_defval;
			UInt32.TryParse("", out Room_spaceID_defval);
			pRoom_spaceID.defaultVal = Room_spaceID_defval;
			pRoomModule.propertys["spaceID"] = pRoom_spaceID; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_spaceID.aliasID] = pRoom_spaceID;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(spaceID / 40002).");

			Property pRoom_gameMupe = new Property();
			pRoom_gameMupe.name = "gameMupe";
			pRoom_gameMupe.properUtype = 11;
			pRoom_gameMupe.properFlags = 4;
			pRoom_gameMupe.aliasID = 4;
			Int32 Room_gameMupe_defval;
			Int32.TryParse("15", out Room_gameMupe_defval);
			pRoom_gameMupe.defaultVal = Room_gameMupe_defval;
			pRoomModule.propertys["gameMupe"] = pRoom_gameMupe; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_gameMupe.aliasID] = pRoom_gameMupe;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(gameMupe / 11).");

			Property pRoom_roomId = new Property();
			pRoom_roomId.name = "roomId";
			pRoom_roomId.properUtype = 9;
			pRoom_roomId.properFlags = 4;
			pRoom_roomId.aliasID = 5;
			Int64 Room_roomId_defval;
			Int64.TryParse("", out Room_roomId_defval);
			pRoom_roomId.defaultVal = Room_roomId_defval;
			pRoomModule.propertys["roomId"] = pRoom_roomId; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_roomId.aliasID] = pRoom_roomId;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(roomId / 9).");

			Property pRoom_roomType = new Property();
			pRoom_roomType.name = "roomType";
			pRoom_roomType.properUtype = 10;
			pRoom_roomType.properFlags = 32;
			pRoom_roomType.aliasID = 6;
			Byte Room_roomType_defval;
			Byte.TryParse("", out Room_roomType_defval);
			pRoom_roomType.defaultVal = Room_roomType_defval;
			pRoomModule.propertys["roomType"] = pRoom_roomType; 

			pRoomModule.usePropertyDescrAlias = true;
			pRoomModule.idpropertys[(UInt16)pRoom_roomType.aliasID] = pRoom_roomType;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), property(roomType / 10).");

			pRoomModule.useMethodDescrAlias = true;
			List<DATATYPE_BASE> pRoom_playPoker_args = new List<DATATYPE_BASE>();
			pRoom_playPoker_args.Add(EntityDef.id2datatypes[23]);

			Method pRoom_playPoker = new Method();
			pRoom_playPoker.name = "playPoker";
			pRoom_playPoker.methodUtype = 48;
			pRoom_playPoker.aliasID = -1;
			pRoom_playPoker.args = pRoom_playPoker_args;

			pRoomModule.methods["playPoker"] = pRoom_playPoker; 
			pRoomModule.cell_methods["playPoker"] = pRoom_playPoker;

			pRoomModule.idcell_methods[pRoom_playPoker.methodUtype] = pRoom_playPoker;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(playPoker / 48).");

			List<DATATYPE_BASE> pRoom_unPlayPoker_args = new List<DATATYPE_BASE>();

			Method pRoom_unPlayPoker = new Method();
			pRoom_unPlayPoker.name = "unPlayPoker";
			pRoom_unPlayPoker.methodUtype = 49;
			pRoom_unPlayPoker.aliasID = -1;
			pRoom_unPlayPoker.args = pRoom_unPlayPoker_args;

			pRoomModule.methods["unPlayPoker"] = pRoom_unPlayPoker; 
			pRoomModule.cell_methods["unPlayPoker"] = pRoom_unPlayPoker;

			pRoomModule.idcell_methods[pRoom_unPlayPoker.methodUtype] = pRoom_unPlayPoker;

			//Dbg.DEBUG_MSG("EntityDef::initScriptModules: add(Room), method(unPlayPoker / 49).");

		}

		public static void initDefTypes()
		{
			{
				UInt16 utype = 2;
				string typeName = "UINT8";
				string name = "UINT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 3;
				string typeName = "UINT16";
				string name = "UINT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 5;
				string typeName = "UINT64";
				string name = "UINT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 4;
				string typeName = "UINT32";
				string name = "UINT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 6;
				string typeName = "INT8";
				string name = "INT8";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 7;
				string typeName = "INT16";
				string name = "INT16";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 8;
				string typeName = "INT32";
				string name = "INT32";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 9;
				string typeName = "INT64";
				string name = "INT64";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 1;
				string typeName = "STRING";
				string name = "STRING";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 12;
				string typeName = "UNICODE";
				string name = "UNICODE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 13;
				string typeName = "FLOAT";
				string name = "FLOAT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 14;
				string typeName = "DOUBLE";
				string name = "DOUBLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PYTHON";
				string name = "PYTHON";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_DICT";
				string name = "PY_DICT";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_TUPLE";
				string name = "PY_TUPLE";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 10;
				string typeName = "PY_LIST";
				string name = "PY_LIST";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 20;
				string typeName = "ENTITYCALL";
				string name = "ENTITYCALL";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 11;
				string typeName = "BLOB";
				string name = "BLOB";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 15;
				string typeName = "VECTOR2";
				string name = "VECTOR2";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 16;
				string typeName = "VECTOR3";
				string name = "VECTOR3";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 17;
				string typeName = "VECTOR4";
				string name = "VECTOR4";
				DATATYPE_BASE val = null;
				EntityDef.datatypes.TryGetValue(name, out val);
				EntityDef.datatypes[typeName] = val;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 22;
				string typeName = "ENTITYLIST";
				DATATYPE_ENTITYLIST datatype = new DATATYPE_ENTITYLIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 23;
				string typeName = "POKERLIST";
				DATATYPE_POKERLIST datatype = new DATATYPE_POKERLIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 24;
				string typeName = "FRIENDLIST";
				DATATYPE_FRIENDLIST datatype = new DATATYPE_FRIENDLIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 25;
				string typeName = "ENTITYDATA";
				DATATYPE_ENTITYDATA datatype = new DATATYPE_ENTITYDATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 26;
				string typeName = "MAILDATA";
				DATATYPE_MAILDATA datatype = new DATATYPE_MAILDATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 27;
				string typeName = "FRIENDDATA";
				DATATYPE_FRIENDDATA datatype = new DATATYPE_FRIENDDATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 28;
				string typeName = "SYNCHRODATA";
				DATATYPE_SYNCHRODATA datatype = new DATATYPE_SYNCHRODATA();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 29;
				string typeName = "MAILLIST";
				DATATYPE_MAILLIST datatype = new DATATYPE_MAILLIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 30;
				string typeName = "FRIENDDATALIST";
				DATATYPE_FRIENDDATALIST datatype = new DATATYPE_FRIENDDATALIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			{
				UInt16 utype = 31;
				string typeName = "SYNCHRODATALIST";
				DATATYPE_SYNCHRODATALIST datatype = new DATATYPE_SYNCHRODATALIST();
				EntityDef.datatypes[typeName] = datatype;
				EntityDef.id2datatypes[utype] = EntityDef.datatypes[typeName];
				EntityDef.datatype2id[typeName] = utype;
			}

			foreach(string datatypeStr in EntityDef.datatypes.Keys)
			{
				DATATYPE_BASE dataType = EntityDef.datatypes[datatypeStr];
				if(dataType != null)
				{
					dataType.bind();
				}
			}
		}

	}


}