/*
	Generated by KBEngine!
	Please do not modify this file!
	
	tools = kbcmd
*/

namespace KBEngine
{
	using UnityEngine;
	using System;
	using System.Collections;
	using System.Collections.Generic;

	// defined in */scripts/entity_defs/Account.def
	public class EntityBaseEntityCall_AccountBase : EntityCall
	{

		public EntityBaseEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_BASE;
		}

		public void getFriendListData()
		{
			Bundle pBundle = newCall("getFriendListData", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void playerAgreeFriend(UInt64 arg1, Byte arg2)
		{
			Bundle pBundle = newCall("playerAgreeFriend", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			bundle.writeUint8(arg2);
			sendCall(null);
		}

		public void playerCreateGame(Int64 arg1)
		{
			Bundle pBundle = newCall("playerCreateGame", 0);
			if(pBundle == null)
				return;

			bundle.writeInt64(arg1);
			sendCall(null);
		}

		public void playerJoinGame(Int64 arg1)
		{
			Bundle pBundle = newCall("playerJoinGame", 0);
			if(pBundle == null)
				return;

			bundle.writeInt64(arg1);
			sendCall(null);
		}

		public void playerLeaveRoom()
		{
			Bundle pBundle = newCall("playerLeaveRoom", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void playerMatchGame()
		{
			Bundle pBundle = newCall("playerMatchGame", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void playerSendMail(UInt64 arg1)
		{
			Bundle pBundle = newCall("playerSendMail", 0);
			if(pBundle == null)
				return;

			bundle.writeUint64(arg1);
			sendCall(null);
		}

		public void reqPlayerMail()
		{
			Bundle pBundle = newCall("reqPlayerMail", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

	}

	public class EntityCellEntityCall_AccountBase : EntityCall
	{

		public EntityCellEntityCall_AccountBase(Int32 eid, string ename) : base(eid, ename)
		{
			type = ENTITYCALL_TYPE.ENTITYCALL_TYPE_CELL;
		}

		public void leaveRoom()
		{
			Bundle pBundle = newCall("leaveRoom", 0);
			if(pBundle == null)
				return;

			sendCall(null);
		}

		public void playerMakeLandlord(SByte arg1, SByte arg2)
		{
			Bundle pBundle = newCall("playerMakeLandlord", 0);
			if(pBundle == null)
				return;

			bundle.writeInt8(arg1);
			bundle.writeInt8(arg2);
			sendCall(null);
		}

		public void setGameReady(SByte arg1)
		{
			Bundle pBundle = newCall("setGameReady", 0);
			if(pBundle == null)
				return;

			bundle.writeInt8(arg1);
			sendCall(null);
		}

		public void stayRoom(Int32 arg1)
		{
			Bundle pBundle = newCall("stayRoom", 0);
			if(pBundle == null)
				return;

			bundle.writeInt32(arg1);
			sendCall(null);
		}

	}
	}
